language: python
python:
- '3.5'
env:
  global:
    - GH_REPO="github.com/firsttris/repository.sendtokodi.git"
    - YOUTUBE_DL="https://github.com/rg3/youtube-dl/archive/master.zip"
    - VERSION_PYTHON3=0.0.${TRAVIS_JOB_NUMBER}
    - ADDON_NAME_PYTHON3="plugin.video.sendtokodi.python3"
    - REPO_NAME="repository.sendtokodi"
    - NAME_PYTHON3="sendtokodi-python3"
script:
- rm -rf .git/
- envsubst < "addon.template.xml" > "addon.xml"
- cd ..
- wget ${YOUTUBE_DL}
- unzip master.zip
- cp -R youtube-dl-master/youtube_dl ${ADDON_NAME_PYTHON3}
- zip -r ${ADDON_NAME_PYTHON3}-${VERSION_PYTHON3}.zip ${ADDON_NAME_PYTHON3}
- git clone https://${GH_REPO}
- cp ${ADDON_NAME_PYTHON3}/addon.xml ${REPO_NAME}/${ADDON_NAME_PYTHON3}/
- cp ${ADDON_NAME_PYTHON3}-${VERSION_PYTHON3}.zip ${REPO_NAME}/${ADDON_NAME_PYTHON3}/
- cd ${REPO_NAME}/
- envsubst < "addon.template.xml" > "addon.xml"
- md5sum addon.xml > addon.xml.md5
- git add .
- git commit -m "Travis-CI Update"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REPO}" master > /dev/null 2>&1